version: '3.8'

# Основной файл с переключением окружений через переменную ENV
# 
# БЕЗОПАСНЫЕ ОКРУЖЕНИЯ (рекомендуемые для обычной работы):
# - ENV=dev-secure (по умолчанию) - разработка с ограниченными правами
# - ENV=prod-secure - продакшн с ограниченными правами
# - ENV=swarm-secure - продакшн в swarm режиме с ограниченными правами
#
# ОКРУЖЕНИЯ С ПОЛНЫМ ДОСТУПОМ К БД (только для миграций):
# - ENV=dev-dbfull - разработка с полными правами (только для миграций!)
# - ENV=prod-dbfull - продакшн с полными правами (только для миграций!)
# - ENV=swarm-dbfull - продакшн в swarm режиме с полными правами (только для миграций!)

# Примеры использования:
# docker-compose up -d                    # dev-secure (по умолчанию)
# ENV=prod-secure docker-compose up -d   # prod-secure
# ENV=dev-dbfull docker-compose up -d    # dev-dbfull (только для миграций!)
# ENV=prod-dbfull docker-compose up -d   # prod-dbfull (только для миграций!)

services:
  frontend:
    extends:
      file: docker-compose.${ENV:-dev-secure}.yml
      service: frontend

  backend:
    extends:
      file: docker-compose.${ENV:-dev-secure}.yml
      service: backend

  db:
    extends:
      file: docker-compose.${ENV:-dev-secure}.yml
      service: db 