version: '3.8'
services:
  frontend:
    environment:
      - FRONT_MODE=dev
    # Для разработки с hot-reload (vite dev)
    volumes:
      - ./client:/app
  backend:
    environment:
      - DEV=true
      - SPRING_PROFILES_ACTIVE=dev
     