version: '3.8'

# Secure версия swarm - наследуем от swarm-dbfull и переопределяем только профиль
services:
  frontend:
    extends:
      file: docker-compose.swarm-dbfull.yml
      service: frontend

  backend:
    extends:
      file: docker-compose.swarm-dbfull.yml
      service: backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod-secure

  db:
    extends:
      file: docker-compose.swarm-dbfull.yml
      service: db 