version: '3.8'
services:
  frontend:
    environment:
      - FRONT_MODE=dev
    # For develope with hot reload (vite dev)
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
