version: '3.8'

# Secure версия swarm с использованием Docker Secrets
services:
  frontend:
    extends:
      file: docker-compose.swarm-dbfull.yml
      service: frontend

  backend:
    extends:
      file: docker-compose.swarm-dbfull.yml
      service: backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod-secure
    secrets:
      - db_password
      - jwt_secret
      - db_username

  db:
    extends:
      file: docker-compose.swarm-dbfull.yml
      service: db
    secrets:
      - db_password

secrets:
  db_password:
    external: true
  jwt_secret:
    external: true
  db_username:
    external: true 